default: &default
  host: localhost
  adapter: postgresql
  pool: 5
  timeout: 5000


development:
  <<: *default
  database: prelaunchr_development
  username: pguser
  password: pguser 

test:
  <<: *default
  database: prelaunchr_test
  username: pguser
  password: pguser

production:
  <<: *default
  database: prelaunchr_test
  username: pguser
  password: pguser